default: &DEFAULT
  jetty_port: 8983
  jetty_home: <%= File.join(ENV['TEST_JETTY_PATH']) || File.join(Rails.root, '../hydra-jetty') %>
  startup_wait: 70
  java_opts:
    - "-XX:+CMSPermGenSweepingEnabled"
    - "-XX:+CMSClassUnloadingEnabled"
    - "-XX:PermSize=64M"
    - "-XX:MaxPermSize=128M"
  quiet: true
test: &TEST
  <<: *DEFAULT
ci:
  <<: *TEST
  startup_wait: 75
  jetty_home: <%= File.join(ENV['TEST_JETTY_PATH']) || Rails.root.join('jetty').to_s %>